//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsForgeSongManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomsForgeSongManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _151 {
            get {
                object obj = ResourceManager.GetObject("_151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ap_pause {
            get {
                object obj = ResourceManager.GetObject("ap_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ap_play {
            get {
                object obj = ResourceManager.GetObject("ap_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ap_stop {
            get {
                object obj = ResourceManager.GetObject("ap_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID.
        /// </summary>
        internal static string AppID {
            get {
                return ResourceManager.GetString("AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID is required..
        /// </summary>
        internal static string AppIDIsRequired {
            get {
                return ResourceManager.GetString("AppIDIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID needs to be 6 characters..
        /// </summary>
        internal static string AppIDNeedsToBe6Characters {
            get {
                return ResourceManager.GetString("AppIDNeedsToBe6Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID needs to be an integer value..
        /// </summary>
        internal static string AppIDNeedsToBeAnIntegerValue {
            get {
                return ResourceManager.GetString("AppIDNeedsToBeAnIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A setlist named &apos;{0}&apos; already exists!.
        /// </summary>
        internal static string ASetlistNamedX0AlreadyExists {
            get {
                return ResourceManager.GetString("ASetlistNamedX0AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backup {
            get {
                object obj = ResourceManager.GetObject("backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap broom {
            get {
                object obj = ResourceManager.GetObject("broom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not include RS2014 base song file/RS1 compatibility files as individual 
        /// songs in a setlist.  Please return to SongManager and 
        ///rescan before returning to Setlist Manager. .
        /// </summary>
        internal static string CanNotIncludeRS1CompatibilityFiles {
            get {
                return ResourceManager.GetString("CanNotIncludeRS1CompatibilityFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not &apos;Select&apos; individual RS1 Compatiblity DLC.
        /// </summary>
        internal static string CanNotSelectIndividualRS1CompatiblityDLC {
            get {
                return ResourceManager.GetString("CanNotSelectIndividualRS1CompatiblityDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cfsm_48x48 {
            get {
                object obj = ResourceManager.GetObject("cfsm_48x48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CGT_Logo {
            get {
                object obj = ResourceManager.GetObject("CGT_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap christmas {
            get {
                object obj = ResourceManager.GetObject("christmas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not extract the audio..
        /// </summary>
        internal static string CouldNotExtractTheAudio {
            get {
                return ResourceManager.GetString("CouldNotExtractTheAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cozy1 {
            get {
                object obj = ResourceManager.GetObject("cozy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap creditsbackground {
            get {
                object obj = ResourceManager.GetObject("creditsbackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap creditsbg {
            get {
                object obj = ResourceManager.GetObject("creditsbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomsForge Song Manager needs to be updated. 
        ///Click the update button to continue.
        ///.
        /// </summary>
        internal static string CustomsForgeSongManagerNeedsToBeUpdatedRNC {
            get {
                return ResourceManager.GetString("CustomsForgeSongManagerNeedsToBeUpdatedRNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dardev {
            get {
                object obj = ResourceManager.GetObject("dardev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap darkseph {
            get {
                object obj = ResourceManager.GetObject("darkseph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete empty directories after renaming.
        /// </summary>
        internal static string DeleteEmptyDirectoriesAfterRenaming {
            get {
                return ResourceManager.GetString("DeleteEmptyDirectoriesAfterRenaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected duplicate CDLC?
        ///Warning:  This can not be undone!.
        /// </summary>
        internal static string DeleteTheSelectedDuplicates {
            get {
                return ResourceManager.GetString("DeleteTheSelectedDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disable {
            get {
                object obj = ResourceManager.GetObject("disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Disabled&apos; is a Reserved Word ...
        ///Setlist names may not contain
        ///any form of the word &apos;disabled&apos;.
        /// </summary>
        internal static string DisabledIsAReservedWord {
            get {
                return ResourceManager.GetString("DisabledIsAReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollarsign {
            get {
                object obj = ResourceManager.GetObject("dollarsign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this CDLC?  {0}Warning:  This cannot be undone!.
        /// </summary>
        internal static string DoYouReallyWantToRemoveThisCDLCX0Warning {
            get {
                return ResourceManager.GetString("DoYouReallyWantToRemoveThisCDLCX0Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DreddFoxx {
            get {
                object obj = ResourceManager.GetObject("DreddFoxx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate File: .
        /// </summary>
        internal static string DuplicateFile {
            get {
                return ResourceManager.GetString("DuplicateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        internal static string Duplicates {
            get {
                return ResourceManager.GetString("Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates Count: {0}.
        /// </summary>
        internal static string DuplicatesCountFormat {
            get {
                return ResourceManager.GetString("DuplicatesCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enabledisable {
            get {
                object obj = ResourceManager.GetObject("enabledisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Enter Value).
        /// </summary>
        internal static string EnterValue {
            get {
                return ResourceManager.GetString("EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EOF20 {
            get {
                object obj = ResourceManager.GetObject("EOF20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EOF201 {
            get {
                object obj = ResourceManager.GetObject("EOF201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Error&gt;.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Error&gt;: No path provided for file scanning.
        /// </summary>
        internal static string ERRORNoPathProvidedForFileScanning {
            get {
                return ResourceManager.GetString("ERRORNoPathProvidedForFileScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Error&gt;: Rocksmith 2014 installation directory setting is null or empty..
        /// </summary>
        internal static string ErrorRocksmith2014InstallationDirectorySet {
            get {
                return ResourceManager.GetString("ErrorRocksmith2014InstallationDirectorySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap extra_data {
            get {
                object obj = ResourceManager.GetObject("extra_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hat {
            get {
                object obj = ResourceManager.GetObject("hat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Log .
        /// </summary>
        internal static string HideLog {
            get {
                return ResourceManager.GetString("HideLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Use:.
        /// </summary>
        internal static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #CFMGrid {
        ///    font-family: &quot;Trebuchet MS&quot;, Arial, Helvetica, sans-serif;
        ///    width: 100%;
        ///    border-collapse: collapse;
        ///    color: #FFFFFF;
        ///    text-align: center;
        ///}
        ///
        ///#CFMGrid td {
        ///    font-size: 1em;
        ///    padding: 3px 7px 2px 7px;
        ///    background-color: #283e4d;
        ///}
        ///
        ///#CFMGrid th {
        ///    font-size: 1.2em;
        ///    padding-top: 5px;
        ///    padding-bottom: 4px;
        ///    color: #ffffff;
        ///    background-color: #1F2D3A;
        ///    border-bottom: 1px solid rgb(30, 139, 195);
        ///}
        ///
        ///#CFMGrid tr.alt td { background-color [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmExport {
            get {
                return ResourceManager.GetString("htmExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap internet {
            get {
                object obj = ResourceManager.GetObject("internet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap launch {
            get {
                object obj = ResourceManager.GetObject("launch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Letter_B {
            get {
                object obj = ResourceManager.GetObject("Letter_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Letter_L {
            get {
                object obj = ResourceManager.GetObject("Letter_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Letter_R {
            get {
                object obj = ResourceManager.GetObject("Letter_R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Letter_V {
            get {
                object obj = ResourceManager.GetObject("Letter_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap load {
            get {
                object obj = ResourceManager.GetObject("load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_black {
            get {
                object obj = ResourceManager.GetObject("logo_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lovroman {
            get {
                object obj = ResourceManager.GetObject("Lovroman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maintenance {
            get {
                object obj = ResourceManager.GetObject("maintenance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved To: .
        /// </summary>
        internal static string MovedTo {
            get {
                return ResourceManager.GetString("MovedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notes {
            get {
                object obj = ResourceManager.GetObject("notes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap onoff {
            get {
                object obj = ResourceManager.GetObject("onoff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter setlist name.
        /// </summary>
        internal static string PleaseEnterSetlistName {
            get {
                return ResourceManager.GetString("PleaseEnterSetlistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan in at least one song..
        /// </summary>
        internal static string PleaseScanInAtLeastOneSong {
            get {
                return ResourceManager.GetString("PleaseScanInAtLeastOneSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select (highlight) the song that 
        /// you would like information about..
        /// </summary>
        internal static string PleaseSelectHighlightTheSongThatNYouWould {
            get {
                return ResourceManager.GetString("PleaseSelectHighlightTheSongThatNYouWould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select (highlight) the song  {0}that you would like to backup..
        /// </summary>
        internal static string PleaseSelectHighlightTheSongX0ThatYouWould {
            get {
                return ResourceManager.GetString("PleaseSelectHighlightTheSongX0ThatYouWould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the checkbox next to songs 
        ///that you would like to delete or move..
        /// </summary>
        internal static string PleaseSelectTheCheckboxNextToSongsNthatYou {
            get {
                return ResourceManager.GetString("PleaseSelectTheCheckboxNextToSongsNthatYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_plus {
            get {
                object obj = ResourceManager.GetObject("refresh_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove spaces from new names
        ///.
        /// </summary>
        internal static string RemoveSpacesFromNewNamesRN {
            get {
                return ResourceManager.GetString("RemoveSpacesFromNewNamesRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename All.
        /// </summary>
        internal static string RenameAll {
            get {
                return ResourceManager.GetString("RenameAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename only the songs that are selected in Song Manager.
        /// </summary>
        internal static string RenameOnlyTheSongsThatAreSelectedInSongMan {
            get {
                return ResourceManager.GetString("RenameOnlyTheSongsThatAreSelectedInSongMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamer.
        /// </summary>
        internal static string Renamer {
            get {
                return ResourceManager.GetString("Renamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] renamer_properties {
            get {
                object obj = ResourceManager.GetObject("renamer_properties", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamer preview : {0}.
        /// </summary>
        internal static string RenamerPreviewX0 {
            get {
                return ResourceManager.GetString("RenamerPreviewX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Template requires &lt;title&gt; to prevent overwriting songs..
        /// </summary>
        internal static string RenameTemplateRequiresTitleToPrevent {
            get {
                return ResourceManager.GetString("RenameTemplateRequiresTitleToPrevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rescan {
            get {
                object obj = ResourceManager.GetObject("rescan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rescan_plus {
            get {
                object obj = ResourceManager.GetObject("rescan_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rescan1 {
            get {
                object obj = ResourceManager.GetObject("rescan1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restorebackup {
            get {
                object obj = ResourceManager.GetObject("restorebackup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restorewindow {
            get {
                object obj = ResourceManager.GetObject("restorewindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rocksmith_2014_Background_Guitar {
            get {
                object obj = ResourceManager.GetObject("Rocksmith_2014_Background_Guitar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocksmith is already running!.
        /// </summary>
        internal static string RocksmithIsAlreadyRunning {
            get {
                return ResourceManager.GetString("RocksmithIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocksmith Song Count: {0}.
        /// </summary>
        internal static string RocksmithSongsCountFormat {
            get {
                return ResourceManager.GetString("RocksmithSongsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RocksmithToolkitGUI_32512 {
            get {
                object obj = ResourceManager.GetObject("RocksmithToolkitGUI_32512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS2014 Installation Directory not found in Registry.
        /// </summary>
        internal static string RS2014InstallationDirectoryNotFoundInRegis {
            get {
                return ResourceManager.GetString("RS2014InstallationDirectoryNotFoundInRegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectCol {
            get {
                object obj = ResourceManager.GetObject("SelectCol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectRow {
            get {
                object obj = ResourceManager.GetObject("SelectRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setlist Manager.
        /// </summary>
        internal static string SetlistManager {
            get {
                return ResourceManager.GetString("SetlistManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shift {
            get {
                object obj = ResourceManager.GetObject("shift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;All.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        internal static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sltsv1_aggregategraph {
            get {
                object obj = ResourceManager.GetObject("sltsv1_aggregategraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The song data has changed.
        ///Do you want to close without saving?.
        /// </summary>
        internal static string SongDataModifiedConfirmation {
            get {
                return ResourceManager.GetString("SongDataModifiedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Manager.
        /// </summary>
        internal static string SongManager {
            get {
                return ResourceManager.GetString("SongManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs Used In Setlists Count: {0}.
        /// </summary>
        internal static string SongsUsedInSetlistsCountFormat {
            get {
                return ResourceManager.GetString("SongsUsedInSetlistsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs Used In Setlists Count: {0}.
        /// </summary>
        internal static string SongsUsedInSetlistsCountX0 {
            get {
                return ResourceManager.GetString("SongsUsedInSetlistsCountX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartRs {
            get {
                object obj = ResourceManager.GetObject("StartRs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag {
            get {
                object obj = ResourceManager.GetObject("tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&apos;The\&apos; Mover e.g., The Beatles -&gt; Beatles, The
        ///.
        /// </summary>
        internal static string TheMoverEGTheBeatlesBeatlesTheRN {
            get {
                return ResourceManager.GetString("TheMoverEGTheBeatlesBeatlesTheRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Rocksmith 1 Compatiblity Song.{0}RS1 Compatiblity Songs can not be disabled individually.{0}Use SetlistManager to disable all RS1 Compatiblity Songs..
        /// </summary>
        internal static string ThisIsARocksmith1CompatiblitySongX0RS1Comp {
            get {
                return ResourceManager.GetString("ThisIsARocksmith1CompatiblitySongX0RS1Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Rocksmith 1 song. It can&apos;t be disabled at this moment. (You just can disable all of them!).
        /// </summary>
        internal static string ThisIsARocksmith1SongItCanTBeDisabled {
            get {
                return ResourceManager.GetString("ThisIsARocksmith1SongItCanTBeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This song is included in a setlist.
        ///Please use Setlist Songs to enable/disable setlist songs..
        /// </summary>
        internal static string ThisSongIsIncludedInASetlist {
            get {
                return ResourceManager.GetString("ThisSongIsIncludedInASetlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the property Key surrounded by \&apos;&lt;\&apos; and \&apos;&gt;\&apos;.  
        ///or simply double click on any Key to the right to
        ///select and build a custom renaming template.
        ///.
        /// </summary>
        internal static string TypeThePropertyKeySurroundedByAndRNorSimpl {
            get {
                return ResourceManager.GetString("TypeThePropertyKeySurroundedByAndRNorSimpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert {0}x{1} image..
        /// </summary>
        internal static string UnableToConvertX0XX1Image {
            get {
                return ResourceManager.GetString("UnableToConvertX0XX1Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a new setlist: \n&lt;Error&gt;: .
        /// </summary>
        internal static string UnableToCreateANewSetlistError {
            get {
                return ResourceManager.GetString("UnableToCreateANewSetlistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete song :{0}{1} &lt;Error&gt;: {2}.
        /// </summary>
        internal static string UnableToDeleteSongX0X1ErrorX2 {
            get {
                return ResourceManager.GetString("UnableToDeleteSongX0X1ErrorX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to enable/disable song: {0} in &apos;dlc&apos; folder.{1}Error: {2}.
        /// </summary>
        internal static string UnableToEnableDisableSongX0InDlcFolderX1Er {
            get {
                return ResourceManager.GetString("UnableToEnableDisableSongX0InDlcFolderX1Er", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move song: {0}, to setlist: {1}{2} &lt;Error&gt;: {3}.
        /// </summary>
        internal static string UnableToMoveSongX0ToSetlistX1X2ErrorX3 {
            get {
                return ResourceManager.GetString("UnableToMoveSongX0ToSetlistX1X2ErrorX3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unleashed2k {
            get {
                object obj = ResourceManager.GetObject("Unleashed2k", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload {
            get {
                object obj = ResourceManager.GetObject("upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Cancelled.
        /// </summary>
        internal static string UserCancelled {
            get {
                return ResourceManager.GetString("UserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;WARNING&gt; User cancelled process ....
        /// </summary>
        internal static string UserCancelledProcess {
            get {
                return ResourceManager.GetString("UserCancelledProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuable Properties.
        /// </summary>
        internal static string UsuableProperties {
            get {
                return ResourceManager.GetString("UsuableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning ... Prevented game hanging{0}{0}Song file: {1}{0}Has already been added to setlest: {2}  {0}First remove the song from the setlist and try again..
        /// </summary>
        internal static string WarningPreventedGameHangingFormat {
            get {
                return ResourceManager.GetString("WarningPreventedGameHangingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to permanently delete all selected songs.{0}{0}Are you sure you want to permanently delete the songs.
        /// </summary>
        internal static string YouAreAboutToPermanentlyDeleteAllSelectedS {
            get {
                return ResourceManager.GetString("YouAreAboutToPermanentlyDeleteAllSelectedS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zip {
            get {
                object obj = ResourceManager.GetObject("zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
