//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsForgeManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomsForgeManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _151 {
            get {
                object obj = ResourceManager.GetObject("151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A setlist named &apos;{0}&apos; already exists!.
        /// </summary>
        internal static string ASetlistNamedX0AlreadyExists {
            get {
                return ResourceManager.GetString("ASetlistNamedX0AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backup {
            get {
                object obj = ResourceManager.GetObject("backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not include RS1 compatibility files as individual 
        /// songs in a setlist.  Please return to SongManager and 
        ///rescan before returning to Setlist Manager. .
        /// </summary>
        internal static string CanNotIncludeRS1CompatibilityFiles {
            get {
                return ResourceManager.GetString("CanNotIncludeRS1CompatibilityFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cfsm_48x48 {
            get {
                object obj = ResourceManager.GetObject("cfsm_48x48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cozy1 {
            get {
                object obj = ResourceManager.GetObject("cozy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created user profile backup:.
        /// </summary>
        internal static string CreatedUserProfileBackup {
            get {
                return ResourceManager.GetString("CreatedUserProfileBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap creditsbackground {
            get {
                object obj = ResourceManager.GetObject("creditsbackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap creditsbg {
            get {
                object obj = ResourceManager.GetObject("creditsbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dardev {
            get {
                object obj = ResourceManager.GetObject("dardev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected duplicate CDLC?
        ///Warning:  This can not be undone!.
        /// </summary>
        internal static string DeleteTheSelectedDuplicates {
            get {
                return ResourceManager.GetString("DeleteTheSelectedDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disable {
            get {
                object obj = ResourceManager.GetObject("disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Disabled&apos; is a Reserved Word ...
        ///Setlist names may not contain
        ///any form of the word &apos;disabled&apos;.
        /// </summary>
        internal static string DisabledIsAReservedWord {
            get {
                return ResourceManager.GetString("DisabledIsAReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this CDLC?  {0}Warning:  This cannot be undone!.
        /// </summary>
        internal static string DoYouReallyWantToRemoveThisCDLCX0Warning {
            get {
                return ResourceManager.GetString("DoYouReallyWantToRemoveThisCDLCX0Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DreddFoxx {
            get {
                object obj = ResourceManager.GetObject("DreddFoxx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate File: .
        /// </summary>
        internal static string DuplicateFile {
            get {
                return ResourceManager.GetString("DuplicateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates Count: {0}.
        /// </summary>
        internal static string DuplicatesCountFormat {
            get {
                return ResourceManager.GetString("DuplicatesCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates need to be rescanned!.
        /// </summary>
        internal static string DuplicatesNeedToBeRescanned {
            get {
                return ResourceManager.GetString("DuplicatesNeedToBeRescanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EOF20 {
            get {
                object obj = ResourceManager.GetObject("EOF20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EOF201 {
            get {
                object obj = ResourceManager.GetObject("EOF201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ERROR&gt;: No path provided for file scanning.
        /// </summary>
        internal static string ERRORNoPathProvidedForFileScanning {
            get {
                return ResourceManager.GetString("ERRORNoPathProvidedForFileScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Rocksmith 2014 installation directory setting is null or empty..
        /// </summary>
        internal static string ErrorRocksmith2014InstallationDirectorySet {
            get {
                return ResourceManager.GetString("ErrorRocksmith2014InstallationDirectorySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///}
        /// table, tr, th 
        /// {
        ///    border-style: solid;
        ///    border-style: outset;
        /// }
        ///td, th 
        ///{ 
        ///    border-style: inset;
        ///
        ///}
        ///.caption 
        ///{ 
        ///    font-weight: bold; 
        ///
        ///}.
        /// </summary>
        internal static string htmExport {
            get {
                return ResourceManager.GetString("htmExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap internet {
            get {
                object obj = ResourceManager.GetObject("internet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap launch {
            get {
                object obj = ResourceManager.GetObject("launch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Letter_B {
            get {
                object obj = ResourceManager.GetObject("Letter_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Letter_L {
            get {
                object obj = ResourceManager.GetObject("Letter_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Letter_R {
            get {
                object obj = ResourceManager.GetObject("Letter_R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Letter_V {
            get {
                object obj = ResourceManager.GetObject("Letter_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap load {
            get {
                object obj = ResourceManager.GetObject("load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_black {
            get {
                object obj = ResourceManager.GetObject("logo_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lovroman {
            get {
                object obj = ResourceManager.GetObject("Lovroman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved To: .
        /// </summary>
        internal static string MovedTo {
            get {
                return ResourceManager.GetString("MovedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No songs found for rename preview..
        /// </summary>
        internal static string NoSongsFoundForRenamePreview {
            get {
                return ResourceManager.GetString("NoSongsFoundForRenamePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter setlist name.
        /// </summary>
        internal static string PleaseEnterSetlistName {
            get {
                return ResourceManager.GetString("PleaseEnterSetlistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan in at least one song..
        /// </summary>
        internal static string PleaseScanInAtLeastOneSong {
            get {
                return ResourceManager.GetString("PleaseScanInAtLeastOneSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select (highlight) the song that 
        /// you would like information about..
        /// </summary>
        internal static string PleaseSelectHighlightTheSongThatNYouWould {
            get {
                return ResourceManager.GetString("PleaseSelectHighlightTheSongThatNYouWould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the checkbox next to songs 
        ///that you would like to delete or move..
        /// </summary>
        internal static string PleaseSelectTheCheckboxNextToSongsNthatYou {
            get {
                return ResourceManager.GetString("PleaseSelectTheCheckboxNextToSongsNthatYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw songs count: {0}.
        /// </summary>
        internal static string RawSongsCountX0 {
            get {
                return ResourceManager.GetString("RawSongsCountX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} obsolete songs..
        /// </summary>
        internal static string RemovedX0ObsoleteSongs {
            get {
                return ResourceManager.GetString("RemovedX0ObsoleteSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] renamer_properties {
            get {
                object obj = ResourceManager.GetObject("renamer_properties", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming From: {0}.
        /// </summary>
        internal static string Renamer_RenamingFrom {
            get {
                return ResourceManager.GetString("Renamer_RenamingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs need to be rescanned with  {0}Song Manager before renaming!.
        /// </summary>
        internal static string Renamer_SongsNeedToBeRescanned {
            get {
                return ResourceManager.GetString("Renamer_SongsNeedToBeRescanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Duplicates to delete/move &apos;{0}&apos; before using Renamer..
        /// </summary>
        internal static string Renamer_UseDuplicatesToDeleteMove {
            get {
                return ResourceManager.GetString("Renamer_UseDuplicatesToDeleteMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamer preview : {0}.
        /// </summary>
        internal static string RenamerPreviewX0 {
            get {
                return ResourceManager.GetString("RenamerPreviewX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Template requires &lt;title&gt; to prevent overwriting songs..
        /// </summary>
        internal static string RenameTemplateRequiresTitleToPrevent {
            get {
                return ResourceManager.GetString("RenameTemplateRequiresTitleToPrevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rescan {
            get {
                object obj = ResourceManager.GetObject("rescan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rocksmith_2014_Background_Guitar {
            get {
                object obj = ResourceManager.GetObject("Rocksmith_2014_Background_Guitar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocksmith 2014 user profile not found!.
        /// </summary>
        internal static string Rocksmith2014UserProfileNotFound {
            get {
                return ResourceManager.GetString("Rocksmith2014UserProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocksmith is already running!.
        /// </summary>
        internal static string RocksmithIsAlreadyRunning {
            get {
                return ResourceManager.GetString("RocksmithIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocksmith Songs Count: {0}.
        /// </summary>
        internal static string RocksmithSongsCountFormat {
            get {
                return ResourceManager.GetString("RocksmithSongsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RocksmithToolkitGUI_32512 {
            get {
                object obj = ResourceManager.GetObject("RocksmithToolkitGUI_32512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS2014 Installation Directory not found in Registry.
        /// </summary>
        internal static string RS2014InstallationDirectoryNotFoundInRegis {
            get {
                return ResourceManager.GetString("RS2014InstallationDirectoryNotFoundInRegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Songs in SongManager Count: {0}.
        /// </summary>
        internal static string SelectedSongsInSongManagerCountX0 {
            get {
                return ResourceManager.GetString("SelectedSongsInSongManagerCountX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;All.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The song data has changed.
        ///Do you want to close without saving?.
        /// </summary>
        internal static string SongDataModifiedConfirmation {
            get {
                return ResourceManager.GetString("SongDataModifiedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs need to be rescanned with  {0}Song Manager before renaming!.
        /// </summary>
        internal static string SongsNeedToBeRescannedWithX0SongManagerBef {
            get {
                return ResourceManager.GetString("SongsNeedToBeRescannedWithX0SongManagerBef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs Used In Setlists Count: {0}.
        /// </summary>
        internal static string SongsUsedInSetlistsCountFormat {
            get {
                return ResourceManager.GetString("SongsUsedInSetlistsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartRs {
            get {
                object obj = ResourceManager.GetObject("StartRs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Rocksmith 1 song. It can&apos;t be disabled at this moment. (You just can disable all of them!).
        /// </summary>
        internal static string ThisIsARocksmith1SongItCanTBeDisabled {
            get {
                return ResourceManager.GetString("ThisIsARocksmith1SongItCanTBeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This song is included in a setlist.
        ///Please use Setlist Songs to enable/disable setlist songs..
        /// </summary>
        internal static string ThisSongIsIncludedInASetlist {
            get {
                return ResourceManager.GetString("ThisSongIsIncludedInASetlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a new setlist: \nError: .
        /// </summary>
        internal static string UnableToCreateANewSetlistError {
            get {
                return ResourceManager.GetString("UnableToCreateANewSetlistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unleashed2k {
            get {
                object obj = ResourceManager.GetObject("Unleashed2k", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload {
            get {
                object obj = ResourceManager.GetObject("upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Canceled.
        /// </summary>
        internal static string UserCanceled {
            get {
                return ResourceManager.GetString("UserCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User canceled process ....
        /// </summary>
        internal static string UserCanceledProcess {
            get {
                return ResourceManager.GetString("UserCanceledProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Duplicates tabmenu to delete/move{0}duplicates before attempting to use Renamer..
        /// </summary>
        internal static string UseTheDuplicatesTabmenuToDeleteMoveX0Dupli {
            get {
                return ResourceManager.GetString("UseTheDuplicatesTabmenuToDeleteMoveX0Dupli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning ... Prevented game hanging{0}{0}Song file: {1}{0}Has already been added to setlest: {2}  {0}First remove the song from the setlist and try again..
        /// </summary>
        internal static string WarningPreventedGameHangingFormat {
            get {
                return ResourceManager.GetString("WarningPreventedGameHangingFormat", resourceCulture);
            }
        }
    }
}
